package commonLLDQuestions.distributedId;

import commonLLDQuestions.distributedId.service.IdGeneratorService;
import commonLLDQuestions.distributedId.strategy.SnowflakeStrategy;

public class DistributedIdGenerator {

    public static void main(String[] args) {

        IdGeneratorService idGeneratorService = new IdGeneratorService(SnowflakeStrategy.getInstance());

        Runnable task = () -> {
            long uniqueId = idGeneratorService.generateUniqueId();
            System.out.println("The unique id generated by thread " +  Thread.currentThread().getName() + " is: " + uniqueId);
        };

        for(int i=0;i<10;i++) {
            Thread thread = new Thread(task);
            thread.start();
        }
    }
}
